### ISSUE TITLE
Switch to Automake 1.17 for autotool files generation

### ISSUE THREAD

**Issue by chenrui333** [libsdl-org/SDL_image#490] opened 2024-12-18 23:50 UTC
👋 It might be better to use Automake 1.17 (the latest version) to regenerate the autotools files.

```
  ==> make install
  CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash '/tmp/sdl2_image-20241218-9726-skc7f/SDL2_image-2.8.3/missing' aclocal-1.16 -I acinclude
  /tmp/sdl2_image-20241218-9726-skc7f/SDL2_image-2.8.3/missing: line 81: aclocal-1.16: command not found
  WARNING: 'aclocal-1.16' is missing on your system.
           You should only need it if you modified 'acinclude.m4' or
           'configure.ac' or m4 files included by 'configure.ac'.
           The 'aclocal' program is part of the GNU Automake package:
           <https://www.gnu.org/software/automake>
           It also requires GNU Autoconf, GNU m4 and Perl in order to run:
           <https://www.gnu.org/software/autoconf>
           <https://www.gnu.org/software/m4/>
           <https://www.perl.org/>
  make: *** [Makefile:656: aclocal.m4] Error 127
```

relates to https://github.com/Homebrew/homebrew-core/pull/201696

**Comment by sezero** [comment] 2024-12-19 06:52
We can do that but the underlying packaging issue will remain and will show itself on systems where system-installed automake != 1.16.5: The source package does have everything updated / regenerated, but the timestamps are bad because of git. For that I had added a `touch-autofoo.sh` script which fixes those things. The source package should be generated after running it. (Or, `autogen.sh` should be run to regenerate everything which also will fix the timestamps.)

**Comment by sezero** [comment] 2024-12-19 07:26
Well, either that, or I can add `AM_MAINTAINER_MODE` to configure.ac to ignore timestamp differences but that will invite more packaging problems, i.e. where one makes changes to configure.ac and/or Makefile.am but forgets regenerating with autogen.sh.

Either way, I am not going to ugprade to automake-1.17 only because of the reported issue, because it is not the root cause of things.

**Comment by sezero** [comment] 2024-12-20 07:32
I don't think I have anything to do here, but still haven't closed, because (i) if CI is responsible for source package generation then @madebr needs to do something about it as I explained above, and/or (ii) if @slouken manually generates source packages then his release-checklist needs adding aututools regeneration steps as I noted above.

Feel free to close this yourself when you guys do those.

**Comment by madebr** [comment] 2024-12-20 07:55
The release scripts simply zips up the git tree, removes .git* files and adds .git-hash and REVISION.TXT.  Automaker is only used for SDL2's mingw builds. Not sure what I need to do.

**Comment by sezero** [comment] 2024-12-20 08:21
> The release scripts simply zips up the git tree, removes .git* files and adds .git-hash and REVISION.TXT. 
> [...] Not sure what I need to do.

In addition to those performed tasks, you can run touch-autofoo.sh to fix timestamps of autotools files' timestamps: that assumes all autotools stuff is already regenerated (the opposite is a maintenance error, already..)

**Comment by madebr** [comment] 2024-12-20 12:07
Why is `touch-autofoo.sh` only in SDL_image?

I'll translate the script in python-ese. Are there other files, besides aclocal.m4, configure, Makefile.in, and test/Makefile.in that need to be touched?
I'd do this for all SDL repos.

**Comment by sezero** [comment] 2024-12-20 12:21
> Why is `touch-autofoo.sh` only in SDL_image?

It is in all automake-using SDL libraries, i.e. SDL_image, SDL_net, SDL_ttf and SDL_rtf. I had made it as a quick'n'dirty maintainer script.

> I'll translate the script in python-ese.

OK I guess

> Are there other files, besides aclocal.m4, configure, Makefile.in, and test/Makefile.in that need to be touched?

No, only those ones in the automake-using SDL libs. (Since we don't rely on an autoconf-generated config.h.in, those are the only ones need touching.)

> I'd do this for all SDL repos.

Only those I listed above need it, i.e. the ones relying on automake. SDL itself and SDL_mixer, do not.

**Comment by sezero** [comment] 2024-12-26 22:01
The new 2.8.4 release has the same issue: neither `touch-autofoo.sh` nor `autogen.sh` seem to have been run before generating the source tarball.

**Comment by madebr** [comment] 2024-12-27 16:21
Makefile.in, aclocal.m4 and configure are touched in 0b79762f0a7da2aa05f0673d367994f7eb9ad812 (SDL2) and ed5d55b750dc48c2b5fdaa6660b2da3ad34bb547 (2.8.x)

**Comment by sezero** [comment] 2024-12-27 16:31
The source pkgs look OK

**Comment by madebr** [comment] 2024-12-27 16:44
In case you want to verify, here are artifacts for:
- SDL2_mixer: https://github.com/madebr/SDL_mixer/actions/runs/12518065430
- SDL2_net: https://github.com/madebr/SDL_net/actions/runs/12517992411
- SDL2_ttf: https://github.com/madebr/SDL_ttf/actions/runs/12517995409

**Comment by sezero** [comment] 2024-12-27 17:14
> In case you want to verify, here are artifacts for:
> 
>     * SDL2_mixer: https://github.com/madebr/SDL_mixer/actions/runs/12518065430
>     * SDL2_net: https://github.com/madebr/SDL_net/actions/runs/12517992411
>     * SDL2_ttf: https://github.com/madebr/SDL_ttf/actions/runs/12517995409

- SDL2_mixer does have the patched_time code in python but doesn't actually need it. The src artifact is thus good.
- SDL2_ttf does have the patched_time code in python, and the rsc artifact looks good
- SDL2_net does _not_ have the patched_time code in python, src artifact is thus _bad_

(P.S.: SDL2_rtf doesn't have anything)

**Comment by madebr** [comment] 2024-12-27 17:33
>     * SDL2_net does _not_ have the patched_time code in python, src artifact is thus _bad_

You're right. Fixed in https://github.com/libsdl-org/SDL_net/actions/runs/12518922068


> (P.S.: SDL2_rtf doesn't have anything)

There was no intention to do a release, so I left it alone.

**Comment by sezero** [comment] 2024-12-27 17:42
> > ```
> > * SDL2_net does _not_ have the patched_time code in python, src artifact is thus _bad_
> > ```
> 
> You're right. Fixed in https://github.com/madebr/SDL_net/actions/runs/12518961995

Src tarball looks good

> > (P.S.: SDL2_rtf doesn't have anything)
> 
> There was no intention to do a release, so I left it alone.

OK

**Comment by sezero** [comment] 2024-12-27 17:47
This happened in my fork
https://github.com/sezero/SDL_net/actions/runs/12518967898/job/34922259837
```
Run .github/fetch_sdl_vc.ps1
  .github/fetch_sdl_vc.ps1
  echo "SDL2_DIR=$Env:GITHUB_WORKSPACE/SDL2-devel-VC" >> $Env:GITHUB_ENV
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
.github/fetch_sdl_vc.ps1: D:\a\_temp\cb1fab8e-bcd4-4a1f-9612-3f755d011297.ps1:2
Line |
   2 |  .github/fetch_sdl_vc.ps1
     |  ~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '.github/fetch_sdl_vc.ps1' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
Error: Process completed with exit code 1.
```

**Comment by madebr** [comment] 2024-12-27 17:48
> This happened in my fork https://github.com/sezero/SDL_net/actions/runs/12518967898/job/34922259837

Mine too :)
I just pushed a fix

**Comment by sezero** [comment] 2024-12-27 17:50
> > This happened in my fork https://github.com/sezero/SDL_net/actions/runs/12518967898/job/34922259837
> 
> Mine too :) I just pushed a fix

Issue may or may not be present in other satellite libs: don't know because the latest commits in SDL2 branches were marked to run CI builders.

**Comment by madebr** [comment] 2024-12-27 17:54
> Issue may or may not be present in other satellite libs: don't know because the latest commits in SDL2 branches were marked to run CI builders.

I don't think so. I converted the ci script of the other satellite libraries to use libsdl-org/setup-sdl. SDL2_net was forgotten.
I'm seeing an issue with SDL2_net's autotools.

**Comment by sezero** [comment] 2024-12-27 17:56
OK

**Comment by sezero** [comment] 2024-12-27 17:58
> I'm seeing an issue with SDL2_net's autotools.

This, in mingw32/autotools build? Don't know why it's happening..

```
checking for pkg-config... /mingw32/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for sdl2 >= 2.0.4... no
checking for sdl2-config... no
checking for SDL - version >= 2.0.4... no
*** The sdl2-config script installed by SDL could not be found
*** If SDL was installed in PREFIX, make sure PREFIX/bin is in
configure: error: *** SDL version 2.0.4 not found!
*** your path, or set the SDL2_CONFIG environment variable to the
*** full path to sdl2-config.
Error: Process completed with exit code 1.
```

**Comment by madebr** [comment] 2024-12-27 18:00
> This, in mingw32/autotools build? Don't know why it's happening..


Fixed it. I forgot about this line when copying from SDL2_images's ci script.

**Comment by sezero** [comment] 2024-12-27 18:04
> Fixed it. I forgot about this line when copying from SDL2_image's ci script.

Yes, looks good

We can close this, if nothing else is left to do.

**Comment by madebr** [comment] 2024-12-27 18:05
Let's bring this to a close then :)

**Closed by madebr** 2024-12-27 18:05 UTC

**Comment by slouken** [comment] 2025-01-04 14:15
Yep, sorry about the hassle.
